version: "3"

services:
  ce.server:
    build:
      context: .
      dockerfile: Dockerfile
    image: crypto-exchange
    ports:
      - "${PORT:-8080}:80"
    networks:
      - meald
    volumes:
      - ".:/var/www/html"